version: '2'
services:

    app:
      build:
        context: .
        dockerfile: docker/app.docker
      depends_on:
        - db
      volumes:
        - ./laravel:/var/www
      working_dir: /var/www
      restart: always

    web:
      build:
        context: .
        dockerfile: docker/web.docker
      depends_on:
        - app
      volumes_from:
        - app
      working_dir: /var/www
      ports:
        - "8090:80"
      restart: always

    db:
      image: mysql
      restart: always
      volumes:
       - ./data/mysql:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: app
        MYSQL_PASSWORD: secret

    pma:
      image: phpmyadmin/phpmyadmin
      depends_on:
        - db
      links:
        - db:mysql
      ports:
        - "8091:80"
      environment:
        PMA_HOST: mysql
        MYSQL_ROOT_PASSWORD: secret
      restart: always

    selenium:
      image: selenium/standalone-chrome
      depends_on:
       - app
      volumes:
       - /dev/shm:/dev/shm
      restart: always
