version: '2'

services:
   db:
     image: mysql:5.7
     volumes:
       - ./dump:/docker-entrypoint-initdb.d     
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: secret
       MYSQL_DATABASE: zvit
       MYSQL_USER: zvit
       MYSQL_PASSWORD: zvit2012

   app:
     depends_on:
       - db
     links:
       - db:mysql
     build: ./docker
     volumes:
       - ./app:/var/www/html
     ports:
       - "8080:80"
     restart: always

   pma:
     image: phpmyadmin/phpmyadmin
     depends_on:
       - db
     links:
       - db:mysql
     ports:
       - "8081:80"
     environment:
       PMA_HOST: mysql
       MYSQL_ROOT_PASSWORD: zvit
     restart: always

