version: "2"
services:

  app:
    build: .
    volumes:
      - ./:/app
    ports:
      - "8080:8000"
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.1.6"
    command: php -S 0.0.0.0:8000 -t /app/src
    restart: "always"
    working_dir: /app
