version: '2'
services:

    app:
      build:
        context: .
        dockerfile: docker/app.docker
      depends_on:
        - db
      volumes:
        - ./laravel:/var/www
      working_dir: /var/www
      restart: always

    web:
      build:
        context: .
        dockerfile: docker/web.docker
      depends_on:
        - app
      volumes_from:
        - app
      working_dir: /var/www
      ports:
        - "8080:80"
      restart: always

    db:
      image: mysql:5.7
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: app
        MYSQL_PASSWORD: secret

    pma:
      image: phpmyadmin/phpmyadmin
      depends_on:
        - db
      links:
        - db:mysql
      ports:
        - "8081:80"
      environment:
        PMA_HOST: mysql
        MYSQL_ROOT_PASSWORD: secret
      restart: always
      
    chrome:
      image: robcherry/docker-chromedriver
      environment:
        CHROMEDRIVER_WHITELISTED_IPS: ""
        CHROMEDRIVER_PORT: "9515"
      ports:
        - 9515:9515
      cap_add:
        - "SYS_ADMIN"
      restart: always
